/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bug_introducer;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        BugIntroducerMiner classUnderTest = new BugIntroducerMiner();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
